### ISSUE TITLE
懒加载

### ISSUE THREAD

**Issue by levy9527** [FEMessage/data-list#4]
加个属性：lazy, 默认 `false`
当为 `true` 时，只有列表在可视区显可见的时候才发送请求。

**Comment by xrr2016** [comment]
vue-infinite-loading 默认是在组件在页面中可视的时候加载数据的

[链接](https://github.com/PeachScript/vue-infinite-loading/blob/ccf1a2084d5be088769d2910057e3c548d5a7457/src/components/InfiniteLoading.vue#L151)

**Comment by xrr2016** [comment]
> 加个属性：lazy, 默认 `false`
> 当为 `true` 时，只有列表在可视区显可见的时候才发送请求。

查阅 vue-infinite-loading 源码发现，它默认是在组件在页面中可视的时候加载数据的

[链接](https://github.com/PeachScript/vue-infinite-loading/blob/ccf1a2084d5be088769d2910057e3c548d5a7457/src/components/InfiniteLoading.vue#L151)

**Comment by kg88** [comment]
@levy9527 
我试了下，当data-list组件在父元素的style设置为display:none的时候，本来就不发送请求啊，您说情况貌似不存在啊？？

**Comment by levy9527** [comment]
> @levy9527
> 我试了下，当data-list组件在父元素的style设置为display:none的时候，本来就不发送请求啊，您说情况貌似不存在啊？？

你好，这个issue应该是过时了，我现在关闭掉，感谢你的关注。
