### ISSUE TITLE
支持修改loading spinner类型及样式

### ISSUE THREAD

**Issue by zcqno1** [FEMessage/data-list#57]
**Is your feature request related to a problem? Please describe.**
目前只提供 `vue-infinite-loading` 的默认 spinner 样式，无法修改

**Describe the solution you'd like**
- `vue-infinite-loading` 提供有若干种不同类型 spinner ，可支持选择这些样式
- 提供 `slot` 让用户自定义样式

**Additional context**
默认 spinner
![image](https://user-images.githubusercontent.com/11766057/63012731-507d5c00-bebd-11e9-8510-f6058b30605f.png)

**Comment by levy9527** [comment]
你好，对于修改 spinner样式，本身是可以做到的，直接传 spinner="waveDots" 即可。

对于slot，在第59个pr中提供支持
