### ISSUE TITLE
希望加载到底后可以有一个事件通知

### ISSUE THREAD

**Issue by zcqno1** [FEMessage/data-list#58]
**Is your feature request related to a problem? Please describe.**
加载到最后一页，没有更多数据时，目前外部无法方便得知这一状态，暂且只能借助 `loaded` 事件根据每次请求结果的数据条数及 `size` 对比来判断，不是很方便。

**Describe the solution you'd like**
在请求到最后一页并完成请求时，触发一个事件（如 `complete`） ，用户可以使用该事件做相应业务处理。

**Comment by levy9527** [comment]
收到
