### ISSUE TITLE
上滚至第1页后调用reset方法，列表清空而无重新请求

### ISSUE THREAD

**Issue by zcqno1** [FEMessage/data-list#78]
## Describe the bug
从非第 1 页开始上滚动加载至第 1 页后，调用 `reset` 方法，列表数据清空，但没有新请求发起

## To Reproduce
1. 开启保存查询参数至url，即默认的 saveQuery=true
2. 列表下滚到第 2 页或之后
3. 刷新页面（reload），列表开始从第 2 页或更后的页开始加载，然后向上滚动至第 1 页
4. 调用内部的 `reset` 方法
5. 结果列表数据被清空，但没有新的请求发起

## Expected behavior
上滚至第 1 页后调用 `reset` 方法可以正常重置然后加载第 1 页数据

## environment information
 - Version : ^1.2.0
 - OS: win10
 - Browser: chrome

## Reason
上滚至第 1 页后，没有将 `canPrev` 置为 `false` ，导致 `direction` 为 `top` 的 `infinite-loading` 一直存在，在调用 `reset` 方法后， `direction=top` 的这个 `infinite-loading` 会优先触发 `infinite` 事件。
但在 `_getList` 方法中判断了如果在第 1 页上滚则返回，从而出现所描述的问题。

## Screenshots
![image](https://user-images.githubusercontent.com/11766057/66383298-5724dd00-e9ef-11e9-98aa-a3f5c5da3529.png)
![image](https://user-images.githubusercontent.com/11766057/66383371-71f75180-e9ef-11e9-8464-7c77b668ac24.png)

**Comment by shoyuf** [comment]
尝试手动设置 `forceUseInfiniteWrapper` ?
