### ISSUE TITLE
Keep loading even API callback empty content

### ISSUE THREAD

**Issue by lianghx-319** [FEMessage/data-list#80]
## Describe the bug
Unexpected keep loading when there is no data

## Screenshots
![image](https://user-images.githubusercontent.com/27187946/67074068-f77ebc80-f1ba-11e9-8798-0837ee158fb4.png)

## To Reproduce
1. yarn add data-list@1.2.1
2. an API with empty content array
3. keep loading

## Expected behavior
If API callback an empty content, it should show no-data or no-result

## environment information
 - Version 1.2.1
 - OS: MacOS
 - Browser Chrome

**Comment by donaldshen** [comment]
当以下情景同时发生时，data-list会卡在loading状态：
1. query的page非第一页
2. 用户刷新，后台返回的数据显示该page数据为空
3. 且totalPages不等于page

**Comment by lianghx-319** [comment]
![image](https://user-images.githubusercontent.com/27187946/67098151-3712cc00-f1ee-11e9-8e35-e102e5b9c4e7.png)
pages 是 1 的时候也出现了
