### ISSUE TITLE
datalist 无法单独获取接口返回的数据

### ISSUE THREAD

**Issue by binonxia** [FEMessage/data-list#9]
**Describe the bug**
1. this.$refs.dataList.getList() 和this.$refs.dataList.list无法使用。
2. 无法获取接口返回的totalElements

**Screenshots**
![Screen Shot 2019-05-20 at 14 29 41](https://user-images.githubusercontent.com/16565919/58001000-e26b0800-7b0c-11e9-934e-7eb61e481fde.png)
![Screen Shot 2019-05-20 at 14 30 20](https://user-images.githubusercontent.com/16565919/58001009-e72fbc00-7b0c-11e9-86b7-bcb4351ce514.png)

**To Reproduce**
1. Go to '秀域微信端/store-list'
2. Click on 'this.$nextTick(async () => {
        this.$refs.dataList.getList()
        // this.$refs.dataList.list
      })'
3. See error

**Expected behavior**
1. this.$refs.dataList.getList() 和this.$refs.dataList.list可以使用。
2. 获取接口返回的除了list以外的分页数据：比如totalElements

**Comment by donaldshen** [comment]
1. `this.$refs.dataList.getList`是内部方法，需要特定参数且并不返回任何结果
2. `this.$refs.dataList.list`看上去正常，存在不可使用的情景吗？
3. 在loaded事件中增加第二个参数res，指向接口请求的返回结果，是否能满足你的需求？

**Comment by binonxia** [comment]
> 1. `this.$refs.dataList.getList`是内部方法，需要特定参数且并不返回任何结果
> 2. `this.$refs.dataList.list`看上去正常，存在不可使用的情景吗？
> 3. 在loaded事件中增加第二个参数res，指向接口请求的返回结果，是否能满足你的需求？
2. 什么叫做`this.$refs.dataList.list`看上去正常，你把代码拉去测试啊。无法获取list
3. 我可以请求两次同一接口，但是为了请求一个字段，我要http两遍。你觉得好吗？
